<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ModMiiDownloader</AssemblyName>
    <RootNamespace>ModMiiDownloader</RootNamespace>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Svg" Version="3.4.7" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Costura.Fody" Version="5.7.0" PrivateAssets="all" />
    <PackageReference Include="Fody" Version="6.8.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="assets\*.svg" />
    <None Remove="assets\icon.png" />
    <EmbeddedResource Include="assets\*.svg" LogicalName="assets/%(Filename)%(Extension)" />
    <EmbeddedResource Include="assets\icon.png" LogicalName="assets/icon.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="downloader.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
