# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QGridLayout, QGroupBox,
    QLabel, QListView, QMainWindow, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QWidget)

from DownloadWidgets import DownloadListSection
from d2xCheckGrid import d2xCheckGrid
from waninCheckGrid import waninCheckGrid
import rc_resource

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(800, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/base/mainIcon", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setIconSize(QSize(32, 32))
        mainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 800, 720))
        self.tabWidget.setDocumentMode(True)
        self.nus = QWidget()
        self.nus.setObjectName(u"nus")
        self.gridLayoutWidget = QWidget(self.nus)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 0, 800, 681))
        self.nusLayout = QGridLayout(self.gridLayoutWidget)
        self.nusLayout.setSpacing(5)
        self.nusLayout.setObjectName(u"nusLayout")
        self.nusLayout.setContentsMargins(0, 0, 0, 0)
        self.channels = DownloadListSection(self.gridLayoutWidget)
        self.channels.setObjectName(u"channels")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.channels.sizePolicy().hasHeightForWidth())
        self.channels.setSizePolicy(sizePolicy1)
        self.channels.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.nusLayout.addWidget(self.channels, 1, 1, 1, 1)

        self.other = DownloadListSection(self.gridLayoutWidget)
        self.other.setObjectName(u"other")
        sizePolicy1.setHeightForWidth(self.other.sizePolicy().hasHeightForWidth())
        self.other.setSizePolicy(sizePolicy1)
        self.other.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.nusLayout.addWidget(self.other, 1, 2, 1, 1)

        self.sysmenus = DownloadListSection(self.gridLayoutWidget)
        self.sysmenus.setObjectName(u"sysmenus")
        sizePolicy1.setHeightForWidth(self.sysmenus.sizePolicy().hasHeightForWidth())
        self.sysmenus.setSizePolicy(sizePolicy1)
        self.sysmenus.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.nusLayout.addWidget(self.sysmenus, 0, 0, 1, 1)

        self.realsigned = DownloadListSection(self.gridLayoutWidget)
        self.realsigned.setObjectName(u"realsigned")
        sizePolicy1.setHeightForWidth(self.realsigned.sizePolicy().hasHeightForWidth())
        self.realsigned.setSizePolicy(sizePolicy1)
        self.realsigned.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.nusLayout.addWidget(self.realsigned, 0, 1, 1, 1)

        self.fakesigned = DownloadListSection(self.gridLayoutWidget)
        self.fakesigned.setObjectName(u"fakesigned")
        sizePolicy1.setHeightForWidth(self.fakesigned.sizePolicy().hasHeightForWidth())
        self.fakesigned.setSizePolicy(sizePolicy1)
        self.fakesigned.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.nusLayout.addWidget(self.fakesigned, 0, 2, 1, 1)

        self.contents = DownloadListSection(self.gridLayoutWidget)
        self.contents.setObjectName(u"contents")
        sizePolicy1.setHeightForWidth(self.contents.sizePolicy().hasHeightForWidth())
        self.contents.setSizePolicy(sizePolicy1)
        self.contents.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.nusLayout.addWidget(self.contents, 1, 0, 1, 1)

        self.tabWidget.addTab(self.nus, "")
        self.wiiHax = QWidget()
        self.wiiHax.setObjectName(u"wiiHax")
        self.gridLayoutWidget_2 = QWidget(self.wiiHax)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(0, 0, 800, 640))
        self.wiiHaxLayout = QGridLayout(self.gridLayoutWidget_2)
        self.wiiHaxLayout.setObjectName(u"wiiHaxLayout")
        self.wiiHaxLayout.setContentsMargins(0, 0, 0, 0)
        self.exploits = DownloadListSection(self.gridLayoutWidget_2)
        self.exploits.setObjectName(u"exploits")
        sizePolicy1.setHeightForWidth(self.exploits.sizePolicy().hasHeightForWidth())
        self.exploits.setSizePolicy(sizePolicy1)
        self.exploits.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.wiiHaxLayout.addWidget(self.exploits, 0, 0, 1, 1)

        self.wiiHomebrew = DownloadListSection(self.gridLayoutWidget_2)
        self.wiiHomebrew.setObjectName(u"wiiHomebrew")
        sizePolicy1.setHeightForWidth(self.wiiHomebrew.sizePolicy().hasHeightForWidth())
        self.wiiHomebrew.setSizePolicy(sizePolicy1)
        self.wiiHomebrew.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.wiiHaxLayout.addWidget(self.wiiHomebrew, 0, 1, 1, 1)

        self.hbc = DownloadListSection(self.gridLayoutWidget_2)
        self.hbc.setObjectName(u"hbc")
        sizePolicy1.setHeightForWidth(self.hbc.sizePolicy().hasHeightForWidth())
        self.hbc.setSizePolicy(sizePolicy1)
        self.hbc.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.wiiHaxLayout.addWidget(self.hbc, 1, 0, 1, 1)

        self.bothHomebrew = DownloadListSection(self.gridLayoutWidget_2)
        self.bothHomebrew.setObjectName(u"bothHomebrew")
        sizePolicy1.setHeightForWidth(self.bothHomebrew.sizePolicy().hasHeightForWidth())
        self.bothHomebrew.setSizePolicy(sizePolicy1)
        self.bothHomebrew.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.wiiHaxLayout.addWidget(self.bothHomebrew, 0, 2, 2, 1)

        self.vWiiHomebrew = DownloadListSection(self.gridLayoutWidget_2)
        self.vWiiHomebrew.setObjectName(u"vWiiHomebrew")
        sizePolicy1.setHeightForWidth(self.vWiiHomebrew.sizePolicy().hasHeightForWidth())
        self.vWiiHomebrew.setSizePolicy(sizePolicy1)
        self.vWiiHomebrew.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.wiiHaxLayout.addWidget(self.vWiiHomebrew, 1, 1, 1, 1)

        self.warning_2 = QLabel(self.wiiHax)
        self.warning_2.setObjectName(u"warning_2")
        self.warning_2.setGeometry(QRect(0, 640, 290, 50))
        font = QFont()
        font.setBold(True)
        self.warning_2.setFont(font)
        self.warning_2.setTextFormat(Qt.TextFormat.AutoText)
        self.warning_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.warning_2.setWordWrap(True)
        self.warning_2.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.tabWidget.addTab(self.wiiHax, "")
        self.themes = QWidget()
        self.themes.setObjectName(u"themes")
        self.themeProtectWarning = QLabel(self.themes)
        self.themeProtectWarning.setObjectName(u"themeProtectWarning")
        self.themeProtectWarning.setGeometry(QRect(210, 630, 240, 60))
        font1 = QFont()
        font1.setBold(True)
        font1.setItalic(True)
        self.themeProtectWarning.setFont(font1)
        self.themeProtectWarning.setTextFormat(Qt.TextFormat.MarkdownText)
        self.themeProtectWarning.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.themeProtectWarning.setWordWrap(True)
        self.themeProtectWarning.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.themeSysmenuWarning = QLabel(self.themes)
        self.themeSysmenuWarning.setObjectName(u"themeSysmenuWarning")
        self.themeSysmenuWarning.setGeometry(QRect(0, 630, 210, 60))
        self.themeSysmenuWarning.setFont(font1)
        self.themeSysmenuWarning.setTextFormat(Qt.TextFormat.MarkdownText)
        self.themeSysmenuWarning.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.themeSysmenuWarning.setWordWrap(True)
        self.themeSysmenuWarning.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.tabWidget.addTab(self.themes, "")
        self.cios = QWidget()
        self.cios.setObjectName(u"cios")
        self.gridLayoutWidget_3 = QWidget(self.cios)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(0, 0, 800, 634))
        self.ciosLayout = QGridLayout(self.gridLayoutWidget_3)
        self.ciosLayout.setObjectName(u"ciosLayout")
        self.ciosLayout.setContentsMargins(0, 0, 0, 0)
        self.wanin = waninCheckGrid(self.gridLayoutWidget_3)
        self.wanin.setObjectName(u"wanin")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.wanin.sizePolicy().hasHeightForWidth())
        self.wanin.setSizePolicy(sizePolicy2)
        self.wanin.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.ciosLayout.addWidget(self.wanin, 0, 1, 2, 1)

        self.hermes = DownloadListSection(self.gridLayoutWidget_3)
        self.hermes.setObjectName(u"hermes")
        self.hermes.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.ciosLayout.addWidget(self.hermes, 0, 2, 1, 1)

        self.d2x = d2xCheckGrid(self.gridLayoutWidget_3)
        self.d2x.setObjectName(u"d2x")
        self.d2x.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.ciosLayout.addWidget(self.d2x, 0, 0, 2, 1)

        self.cmios = DownloadListSection(self.gridLayoutWidget_3)
        self.cmios.setObjectName(u"cmios")
        self.cmios.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.ciosLayout.addWidget(self.cmios, 1, 2, 1, 1)

        self.ciosWarning = QLabel(self.cios)
        self.ciosWarning.setObjectName(u"ciosWarning")
        self.ciosWarning.setGeometry(QRect(0, 630, 210, 60))
        self.ciosWarning.setFont(font)
        self.ciosWarning.setTextFormat(Qt.TextFormat.PlainText)
        self.ciosWarning.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ciosWarning.setWordWrap(True)
        self.ciosWarning.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.ciosNote = QLabel(self.cios)
        self.ciosNote.setObjectName(u"ciosNote")
        self.ciosNote.setGeometry(QRect(210, 630, 220, 60))
        font2 = QFont()
        font2.setBold(False)
        font2.setItalic(True)
        self.ciosNote.setFont(font2)
        self.ciosNote.setTextFormat(Qt.TextFormat.MarkdownText)
        self.ciosNote.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ciosNote.setWordWrap(True)
        self.ciosNote.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.d2xSettings = QPushButton(self.cios)
        self.d2xSettings.setObjectName(u"d2xSettings")
        self.d2xSettings.setGeometry(QRect(710, 635, 91, 50))
        self.wiiRecommended = QPushButton(self.cios)
        self.wiiRecommended.setObjectName(u"wiiRecommended")
        self.wiiRecommended.setGeometry(QRect(430, 635, 140, 50))
        self.vwiiRecommended = QPushButton(self.cios)
        self.vwiiRecommended.setObjectName(u"vwiiRecommended")
        self.vwiiRecommended.setGeometry(QRect(570, 635, 140, 50))
        self.tabWidget.addTab(self.cios, "")
        self.misc = QWidget()
        self.misc.setObjectName(u"misc")
        self.gridLayoutWidget_4 = QWidget(self.misc)
        self.gridLayoutWidget_4.setObjectName(u"gridLayoutWidget_4")
        self.gridLayoutWidget_4.setGeometry(QRect(0, 0, 800, 681))
        self.miscLayout = QGridLayout(self.gridLayoutWidget_4)
        self.miscLayout.setObjectName(u"miscLayout")
        self.miscLayout.setContentsMargins(0, 0, 0, 0)
        self.pc = QGroupBox(self.gridLayoutWidget_4)
        self.pc.setObjectName(u"pc")
        sizePolicy1.setHeightForWidth(self.pc.sizePolicy().hasHeightForWidth())
        self.pc.setSizePolicy(sizePolicy1)
        self.pc.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pcList = QListView(self.pc)
        self.pcList.setObjectName(u"pcList")
        self.pcList.setGeometry(QRect(0, 21, 396, 658))
        sizePolicy.setHeightForWidth(self.pcList.sizePolicy().hasHeightForWidth())
        self.pcList.setSizePolicy(sizePolicy)
        self.pcList.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.pcList.setProperty(u"showDropIndicator", False)
        self.pcList.setAlternatingRowColors(True)
        self.pcList.setSelectionMode(QAbstractItemView.SelectionMode.MultiSelection)
        self.pcList.setUniformItemSizes(False)

        self.miscLayout.addWidget(self.pc, 0, 1, 1, 1)

        self.wiiu = QGroupBox(self.gridLayoutWidget_4)
        self.wiiu.setObjectName(u"wiiu")
        sizePolicy1.setHeightForWidth(self.wiiu.sizePolicy().hasHeightForWidth())
        self.wiiu.setSizePolicy(sizePolicy1)
        self.wiiu.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.wiiuList = QListView(self.wiiu)
        self.wiiuList.setObjectName(u"wiiuList")
        self.wiiuList.setGeometry(QRect(0, 21, 396, 658))
        sizePolicy.setHeightForWidth(self.wiiuList.sizePolicy().hasHeightForWidth())
        self.wiiuList.setSizePolicy(sizePolicy)
        self.wiiuList.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.wiiuList.setProperty(u"showDropIndicator", False)
        self.wiiuList.setAlternatingRowColors(True)
        self.wiiuList.setSelectionMode(QAbstractItemView.SelectionMode.MultiSelection)
        self.wiiuList.setUniformItemSizes(False)

        self.miscLayout.addWidget(self.wiiu, 0, 0, 1, 1)

        self.tabWidget.addTab(self.misc, "")
        self.warning = QLabel(self.centralwidget)
        self.warning.setObjectName(u"warning")
        self.warning.setGeometry(QRect(0, 720, 290, 50))
        self.warning.setFont(font)
        self.warning.setTextFormat(Qt.TextFormat.MarkdownText)
        self.warning.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.warning.setWordWrap(True)
        self.warning.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.download = QPushButton(self.centralwidget)
        self.download.setObjectName(u"download")
        self.download.setGeometry(QRect(690, 720, 110, 50))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.download.setIcon(icon1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        mainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.tabWidget, self.wiiRecommended)
        QWidget.setTabOrder(self.wiiRecommended, self.vwiiRecommended)
        QWidget.setTabOrder(self.vwiiRecommended, self.d2xSettings)
        QWidget.setTabOrder(self.d2xSettings, self.wiiuList)
        QWidget.setTabOrder(self.wiiuList, self.pcList)
        QWidget.setTabOrder(self.pcList, self.download)

        self.retranslateUi(mainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"ModMii", None))
        self.channels.setTitle(QCoreApplication.translate("mainWindow", u"Channels", None))
        self.other.setTitle(QCoreApplication.translate("mainWindow", u"Other WADs", None))
        self.sysmenus.setTitle(QCoreApplication.translate("mainWindow", u"System Menus", None))
        self.realsigned.setTitle(QCoreApplication.translate("mainWindow", u"Non-Fakesigned IOSs\\MIOS", None))
        self.fakesigned.setTitle(QCoreApplication.translate("mainWindow", u"Fakesigned IOSs", None))
        self.contents.setTitle(QCoreApplication.translate("mainWindow", u"Content Files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nus), QCoreApplication.translate("mainWindow", u"NUS Files", None))
        self.exploits.setTitle(QCoreApplication.translate("mainWindow", u"Exploits", None))
        self.wiiHomebrew.setTitle(QCoreApplication.translate("mainWindow", u"Wii-Only Homebrew", None))
        self.hbc.setTitle(QCoreApplication.translate("mainWindow", u"Homebrew Channels", None))
        self.bothHomebrew.setTitle(QCoreApplication.translate("mainWindow", u"Wii && vWii Homebrew", None))
        self.vWiiHomebrew.setTitle(QCoreApplication.translate("mainWindow", u"vWii-Only Homebrew", None))
        self.warning_2.setText(QCoreApplication.translate("mainWindow", u"icon legend here\n"
"icon legend here", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wiiHax), QCoreApplication.translate("mainWindow", u"Wii && vWii Homebrew && Exploits", None))
        self.themeProtectWarning.setText(QCoreApplication.translate("mainWindow", u" DON'T INSTALL THEMES WITHOUT PROTECTION: _BOOTMII, PRIILOADER AND NAND BACKUP_", None))
        self.themeSysmenuWarning.setText(QCoreApplication.translate("mainWindow", u"ONLY INSTALL THEMES FOR _YOUR SPECIFIC SYSTEM MENU VERSION AND REGION!_", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.themes), QCoreApplication.translate("mainWindow", u"System Menu Themes", None))
        self.wanin.setTitle(QCoreApplication.translate("mainWindow", u"Waninkoko cIOSs", None))
        self.hermes.setTitle(QCoreApplication.translate("mainWindow", u"Hermes cIOSs", None))
        self.d2x.setTitle(QCoreApplication.translate("mainWindow", u"d2x-d2xversion cIOSs", None))
        self.cmios.setTitle(QCoreApplication.translate("mainWindow", u"cMIOSs", None))
        self.ciosWarning.setText(QCoreApplication.translate("mainWindow", u"Unrecommended cIOSs are intended for compatibility testing or unique situations", None))
        self.ciosNote.setText(QCoreApplication.translate("mainWindow", u"The number in brackets indicates the base IOS; e.g. cIOS222 [**38**] is an IOS installed to slot 222 based on IOS**38**", None))
        self.d2xSettings.setText(QCoreApplication.translate("mainWindow", u"d2x Version\n"
"Settings", None))
        self.wiiRecommended.setText(QCoreApplication.translate("mainWindow", u"Select Recommended", None))
        self.vwiiRecommended.setText(QCoreApplication.translate("mainWindow", u"Select Recommended\n"
"(vWii)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cios), QCoreApplication.translate("mainWindow", u"cIOSs && cMIOSs", None))
        self.pc.setTitle(QCoreApplication.translate("mainWindow", u"PC Programs", None))
        self.wiiu.setTitle(QCoreApplication.translate("mainWindow", u"Wii U Homebrew", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.misc), QCoreApplication.translate("mainWindow", u"WiiU Homebrew && PC Programs ", None))
        self.warning.setText(QCoreApplication.translate("mainWindow", u"Some of these files *_MAY CAUSE BRICK_* if you do not know what you are doing!", None))
        self.download.setText(QCoreApplication.translate("mainWindow", u"Download", None))
    # retranslateUi

